---
apiVersion: v1
kind: Service
metadata:
  name: demo-web
spec:
  selector:
    app: devops
  ports:
  - name: web
    port: 80
    targetPort: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-web
spec:
  rules:
  - host: app1.local
    http:
      paths:
      - path: /
        backend:
          serviceName: demo-web
          servicePort: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: devops
  name: devops
spec:
  selector:
    matchLabels:
      app: devops
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - image: registry.opensuse.org/home/bdekany/branches/opensuse/templates/images/42.3/containers/demo-devops-app:latest
        name: devops
        ports:
        - containerPort: 9000
          name: devops
---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:4
        name: redis
        ports:
        - containerPort: 6379
          name: redis
